//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transports.Web.Forms.Proxy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Proxy.ITransportsService")]
    public interface ITransportsService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITransportsService/CreateDriver")]
        void CreateDriver(string driver);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITransportsService/CreateDriver")]
        System.Threading.Tasks.Task CreateDriverAsync(string driver);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITransportsServiceChannel : Transports.Web.Forms.Proxy.ITransportsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TransportsServiceClient : System.ServiceModel.ClientBase<Transports.Web.Forms.Proxy.ITransportsService>, Transports.Web.Forms.Proxy.ITransportsService {
        
        public TransportsServiceClient() {
        }
        
        public TransportsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TransportsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransportsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransportsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void CreateDriver(string driver) {
            base.Channel.CreateDriver(driver);
        }
        
        public System.Threading.Tasks.Task CreateDriverAsync(string driver) {
            return base.Channel.CreateDriverAsync(driver);
        }
    }
}
